# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

volumes:
  esdata:
    driver: local

services:
###########################
# Setup the Nginx container
###########################
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./files/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../testapp/:/usr/share/nginx/html

###########################
# Setup the Elasticsearch container
###########################
  elasticsearch1:
    image: elasticsearch:latest
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
